package com.budowlanka.backend.integration;

import static org.hamcrest.Matchers.not;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.budowlanka.backend.IntegrationTestBase;
import com.budowlanka.backend.auth.entity.User;
import com.budowlanka.backend.auth.enums.UserRole;
import com.budowlanka.backend.auth.repository.UserRepository;
import com.budowlanka.backend.auth.service.JwtService;
import java.util.UUID;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.test.web.servlet.MockMvc;

/**
 * Actuator config (REM-171): health/info exposed, liveness/readiness probes, and health details
 * gated to ADMIN via show-details=when-authorized + roles=ADMIN.
 */
@SpringBootTest
@AutoConfigureMockMvc
class ActuatorIntegrationTest extends IntegrationTestBase {

  @Autowired private MockMvc mockMvc;
  @Autowired private UserRepository userRepository;
  @Autowired private JwtService jwtService;

  private User adminUser;
  private User clientUser;
  private String adminToken;
  private String clientToken;

  @BeforeEach
  void setUp() {
    adminUser = saveVerifiedUser("admin-" + UUID.randomUUID() + "@test.com", UserRole.ADMIN);
    clientUser = saveVerifiedUser("client-" + UUID.randomUUID() + "@test.com", UserRole.CLIENT);
    adminToken = jwtService.generateAccessToken(adminUser);
    clientToken = jwtService.generateAccessToken(clientUser);
  }

  @AfterEach
  void tearDown() {
    userRepository.delete(adminUser);
    userRepository.delete(clientUser);
  }

  // ---- health (public status, no details) ----

  @Test
  void should_returnStatusUpWithoutDetails_when_anonymousHitsHealth() throws Exception {
    mockMvc
        .perform(get("/actuator/health"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.status").value("UP"))
        .andExpect(jsonPath("$.components").doesNotExist());
  }

  @Test
  void should_hideDetails_when_authenticatedNonAdminHitsHealth() throws Exception {
    // show-details=when-authorized + roles=ADMIN — a CLIENT is authenticated but not authorized
    mockMvc
        .perform(get("/actuator/health").header("Authorization", "Bearer " + clientToken))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.status").value("UP"))
        .andExpect(jsonPath("$.components").doesNotExist());
  }

  @Test
  void should_exposeComponents_when_adminHitsHealth() throws Exception {
    mockMvc
        .perform(get("/actuator/health").header("Authorization", "Bearer " + adminToken))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.status").value("UP"))
        .andExpect(jsonPath("$.components.db").exists());
  }

  // ---- liveness / readiness probes (public) ----

  @Test
  void should_return200_when_anonymousHitsLivenessProbe() throws Exception {
    mockMvc
        .perform(get("/actuator/health/liveness"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.status").value("UP"));
  }

  @Test
  void should_return200_when_anonymousHitsReadinessProbe() throws Exception {
    mockMvc
        .perform(get("/actuator/health/readiness"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.status").value("UP"));
  }

  // ---- info (public, build metadata) ----

  @Test
  void should_exposeBuildInfo_when_anonymousHitsInfo() throws Exception {
    // build-info.properties generated by spring-boot-maven-plugin (build-info goal)
    mockMvc
        .perform(get("/actuator/info"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.build").exists());
  }

  // ---- other endpoints not exposed ----

  @Test
  void should_return401_when_anonymousHitsNonExposedEndpoint() throws Exception {
    mockMvc.perform(get("/actuator/metrics")).andExpect(status().isUnauthorized());
  }

  @Test
  void should_notServeMetrics_when_adminHitsNonExposedEndpoint() throws Exception {
    // metrics is authorized for ADMIN but not on the web exposure list, so it never returns 200
    // (unknown route -> app's catch-all yields 500; the point is only that it is not exposed).
    mockMvc
        .perform(get("/actuator/metrics").header("Authorization", "Bearer " + adminToken))
        .andExpect(status().is(not(200)));
  }

  private User saveVerifiedUser(String email, UserRole role) {
    return userRepository.save(
        User.builder()
            .email(email)
            .passwordHash("$2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
            .role(role)
            .emailVerified(true)
            .build());
  }
}
